; Inno Setup Script for FUS Testpad (Dev)
; Generated by Codex CLI
; Usage: compile with ISCC. Optionally override version: ISCC /DMyAppVersion=1.10.5 build_config\testpad-dev.iss

#ifndef MyAppVersion
  #define MyAppVersion "1.10.0"
#endif

#define MyCompany       "FUS Instruments"
#define MyCompanyURL    "https://fusinstruments.com"
#define MyAppName       "FUS Testpad (Dev)"
#define MyAppShort      "Testpad Dev"
#define RepoRoot        AddBackslash(SourcePath) + ".."
#define DistDir         AddBackslash(SourcePath) + "..\\dist"
#define BuildFolder     "testpad_dev_v" + MyAppVersion
#define MyAppExeName    "testpad_dev_v" + MyAppVersion + ".exe"

[Setup]
AppId={{0506fd10-210e-453e-b9f8-cf0a6239fafd}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyCompany}
AppPublisherURL={#MyCompanyURL}
AppSupportURL={#MyCompanyURL}
DefaultDirName={autopf}\{#MyCompany}\{#MyAppShort}
DefaultGroupName={#MyCompany}\{#MyAppShort}
OutputDir={#SourcePath}..\installers
OutputBaseFilename=testpad-dev-setup-v{#MyAppVersion}
Compression=lzma2/max
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
PrivilegesRequired=admin
SetupIconFile={#RepoRoot}\src\testpad\resources\fus_icon_transparent.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
WizardStyle=modern
UsePreviousAppDir=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &Desktop shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
Source: "{#DistDir}\{#BuildFolder}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\{#MyAppShort}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppShort}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppShort}"; Flags: nowait postinstall skipifsilent
